//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2.Assignment_4 {
    
    
    public partial class WebForm1 {
        
        /// <summary>
        /// EssayQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion;
        
        /// <summary>
        /// MultipleChoiceQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.MultipleChoiceQuestion MultipleChoiceQuestion;
        
        /// <summary>
        /// TrueFalseQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion;
        
        /// <summary>
        /// ShortTextQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion;
        
        /// <summary>
        /// TestSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button TestSubmit;
        
        /// <summary>
        /// TestLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal TestLiteral;
    }
}
