//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2.Midterm {
    
    
    public partial class MidtermExam {
        
        /// <summary>
        /// uxQuestions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder uxQuestions;
        
        /// <summary>
        /// TrueFalseQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion;
        
        /// <summary>
        /// TrueFalseQuestion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion1;
        
        /// <summary>
        /// TrueFalseQuestion2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion2;
        
        /// <summary>
        /// TrueFalseQuestion3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion3;
        
        /// <summary>
        /// TrueFalseQuestion4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion4;
        
        /// <summary>
        /// TrueFalseQuestion5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion5;
        
        /// <summary>
        /// TrueFalseQuestion6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion6;
        
        /// <summary>
        /// TrueFalseQuestion7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion7;
        
        /// <summary>
        /// TrueFalseQuestion8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion8;
        
        /// <summary>
        /// TrueFalseQuestion9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.TrueFalseQuestion TrueFalseQuestion9;
        
        /// <summary>
        /// EssayQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion;
        
        /// <summary>
        /// EssayQuestion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion1;
        
        /// <summary>
        /// EssayQuestion2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion2;
        
        /// <summary>
        /// EssayQuestion3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion3;
        
        /// <summary>
        /// EssayQuestion4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion4;
        
        /// <summary>
        /// EssayQuestion5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion5;
        
        /// <summary>
        /// EssayQuestion6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.EssayQuestion EssayQuestion6;
        
        /// <summary>
        /// MultipleChoiceQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.MultipleChoiceQuestion MultipleChoiceQuestion;
        
        /// <summary>
        /// MultipleChoiceQuestion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.MultipleChoiceQuestion MultipleChoiceQuestion1;
        
        /// <summary>
        /// MultipleChoiceQuestion2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.MultipleChoiceQuestion MultipleChoiceQuestion2;
        
        /// <summary>
        /// MultipleChoiceQuestion3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.MultipleChoiceQuestion MultipleChoiceQuestion3;
        
        /// <summary>
        /// MultipleChoiceQuestion4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.MultipleChoiceQuestion MultipleChoiceQuestion4;
        
        /// <summary>
        /// ShortTextQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion;
        
        /// <summary>
        /// ShortTextQuestion1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion1;
        
        /// <summary>
        /// ShortTextQuestion2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion2;
        
        /// <summary>
        /// ShortTextQuestion3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion3;
        
        /// <summary>
        /// ShortTextQuestion4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion4;
        
        /// <summary>
        /// ShortTextQuestion5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion5;
        
        /// <summary>
        /// ShortTextQuestion6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Lab2.Assignment_4.ShortTextQuestion ShortTextQuestion6;
        
        /// <summary>
        /// TestSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button TestSubmit;
    }
}
